repo_name: Cntrl Alt Del
repo_url: https://github.com/danilofns/teste
site_name: Cntrl Alt Del
site_url: https://github.com/danilofns/teste
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
  language: pt-BR

extra_css:
  - stylesheets/style.css

nav:
  - Home: index.md
  - Participantes: participantes.md